// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CodewarsTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NextLargeNumber")]
    public partial class NextLargeNumberFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NextLargeNumber.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "NextLargeNumber", "\tIn order 將數字重新組合 \r\n\tAs a user \r\n\tI want to 取得重組下一個較大的數字，如果無法重組出更大的數字回傳-1", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void 取得下一個重組數字(string input, string excepted, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("取得下一個重組數字", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("當我輸入 {0}", input), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When("重組後", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then(string.Format("應該為 {0}", excepted), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 1")]
        public virtual void 取得下一個重組數字_1()
        {
#line 6
this.取得下一個重組數字("1", "-1", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 12")]
        public virtual void 取得下一個重組數字_12()
        {
#line 6
this.取得下一個重組數字("12", "21", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 21")]
        public virtual void 取得下一個重組數字_21()
        {
#line 6
this.取得下一個重組數字("21", "-1", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 345")]
        public virtual void 取得下一個重組數字_345()
        {
#line 6
this.取得下一個重組數字("345", "354", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 576")]
        public virtual void 取得下一個重組數字_576()
        {
#line 6
this.取得下一個重組數字("576", "657", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 2017")]
        public virtual void 取得下一個重組數字_2017()
        {
#line 6
this.取得下一個重組數字("2017", "2071", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 2071")]
        public virtual void 取得下一個重組數字_2071()
        {
#line 6
this.取得下一個重組數字("2071", "2107", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 123456789")]
        public virtual void 取得下一個重組數字_123456789()
        {
#line 6
this.取得下一個重組數字("123456789", "123456798", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 1234567890")]
        public virtual void 取得下一個重組數字_1234567890()
        {
#line 6
this.取得下一個重組數字("1234567890", "1234567908", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 1495941256")]
        public virtual void 取得下一個重組數字_1495941256()
        {
#line 6
this.取得下一個重組數字("1495941256", "1495941265", ((string[])(null)));
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("取得下一個重組數字: 404703381")]
        public virtual void 取得下一個重組數字_404703381()
        {
#line 6
this.取得下一個重組數字("404703381", "404703813", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
